### ISSUE TITLE
Change for the readme

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#101]
It says

> Telemetry packet capture is performed by running the  packetgrab.py  script on the network.

Should be?

> Telemetry packet capture is performed by running the command **packetcapture** on the network.

**Comment by SenorPez** [comment]
Fix included in Release Candidate 4, now pushed to PyPi.

Upgrade by running `pip install --upgrade replayenhancer`

**Comment by Michel-NL** [comment]
👍
