### ISSUE TITLE
Request for features/enhancements display driver pitting

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#107]
Is it possible to show when a driver is doing a pit? 
![pit](https://cloud.githubusercontent.com/assets/16852542/20858989/59470d9a-b952-11e6-8e0b-d69edb8e1dba.jpg)

**Comment by SenorPez** [comment]
Coming soon! The logic from the old infrastructure shouldn't be too hard to port into the current version.

Shows a red "PIT" indicator when the car enters the pits.
Shows a running clock while the car is stopped in the pits.
Shows a stopped clock while the car is leaving the pits.

See an example here:
https://youtu.be/AjCzBwsEtLs?t=457

**Comment by Michel-NL** [comment]
> See an example here:
> https://youtu.be/AjCzBwsEtLs?t=457

That's looking really nice...we want it :)
