### ISSUE TITLE
Extra point for pole position with qualification

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#108]
Just now noticed that AOR is giving the pole position driver 1 extra point. 
Is it possible to give a driver 1 extra point for qualification pole?

Workaround:
I could change the point_structure. Find the driver who has the pole and change the point_structure +1 point.
Say the driver with the pole is finishing at 9th position then he would not have 11 points but 12 points.
But that's easy to forget and after rendering for 7 hours to find out you have to do it again is not making you happy ;-)

  "point_structure" : [ 0, 35, 32, 29, 26, 23, 20, 17, 14, **12**, 9, 7, 5, 4, 3, 2, 1 ],

AOR points:
1st = 35
2nd = 32
3rd = 29
4th = 26
5th = 23
6th = 20
7th = 17
8th = 14
**9th = 11**
10th = 9
11th = 7
12th = 5
13th = 4
14th = 3
15th = 2
16th = 1

Pole Position - 1 point

**Comment by SenorPez** [comment]
For AOR, I'd suggest updating the driver's points before the race (that appear on the title screen) with the Pole Position bonus point. Afterall, by the time we're in the race broadcast, that point has been earned!

However, this raises an enhancement I'd like to make: It can handle this in a different way, in a bit more general way, that will also add some flexibility and solve a longstanding issue.

I'm thinking of adding a field to the "participant_config" entries that will allow you to either straight up SET the driver's points AFTER the race (completely bypassing calculation), or provide an ADJUSTMENT to the driver's points AFTER the race.

Usage examples:
- Set the pole position driver to get "+1" point. His points are calculated from the starting points, points earned for the race, and then +1.
- You want to do something other than the Project CARS Replay Enhancer's default behavior of giving zero points to cars not running at the end. You can manually set those DNF cars points, and they'll be properly included in the series standings. Much easier than, say, trying to build a "race rules" module that you'd configure.
- You want to give multiple points for fastest laps. (Say, in a 50 lap race, each 10 lap segment gets a bonus point.) You'd have to figure out WHO gets the points yourself, but then you can use this to properly display the calculated values.

Additionally, I'd allow fractional points. They wouldn't be displayed; I can't think of a race series in the world that uses fractional points. But what they WOULD allow is the implementation, manually but hidden from the display, of your own tiebreakers. Right now, it's just sorted by points and then by name. If your series uses a countback, and there's a tie, the higher position could get +0.1 points added. The 0.1 won't be displayed, but it'd sort that driver above the one that didn't get a bonus.

**Comment by Michel-NL** [comment]
> For AOR, I'd suggest updating the driver's points before the race (that appear on the title screen) with the Pole Position bonus point. Afterall, by the time we're in the race broadcast, that point has been earned!

You are right about this.

> You want to do something other than the Project CARS Replay Enhancer's default behavior of giving zero points to cars not running at the end. You can manually set those DNF cars points, and they'll be properly included in the series standings. Much easier than, say, trying to build a "race rules" module that you'd configure.

For this I removed the points. In this example I removed the points for the last four cars, because they didn't finish: "point_structure" : [ 0, 35, 32, 29, 26, 23, 20, 17, 14, 11, 9, 7, 5 ],
But instead of 0 points the DNF text would be nice.
