### ISSUE TITLE
Showing 10 instead of 11 drivers in replay

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#109]
Yesterday created a new replay with 11 drivers but in the video it only shows 10 drivers. The starting grid pictures show 11 drivers but as soon as the race starts it are only 10 drivers. During the race 1 driver disconnected.
https://youtu.be/5a0IJ

Config file: (https://github.com/SenorPez/project-cars-replay-enhancer/files/635859/psnracing.txt)

**Comment by SenorPez** [comment]
Did the 11th driver start the race and drop out?
Could you ZIP up the telemetry and send it to me? Multiplayer races are good, because I can catch edge cases like this... he should be showing up!

**Comment by Michel-NL** [comment]
Yes he started the race and had a disconnect.

Telemetry zip: https://1drv.ms/u/s!AkpjgvuA0hKBl6t54saHQTBNN3mnNw

**Comment by Michel-NL** [comment]
In the new version of the configuration editor I see two new lines. 
  "leader_window_size" : 10, 
Is this causing to show only ten drivers? I changed it to eleven, but same result, only showing ten drivers.

What is the meaning of "Leader Standing Lines" and "Target Standings Lines"

Edit:
ok now I have two (how do you call it?) arrays of drivers showing 15 drivers. Have to play some more with these settings I Think :)

**Comment by Michel-NL** [comment]
New race video and data with 15 drivers.
Leader Standing lines 0
Target Standings lines 15 

Now its showing 15 drivers 👍

**Comment by SenorPez** [comment]
Hmm... I'll take a look at this. I'm also going to fix the defaults so they don't break old videos... that's not good behavior on my part.

The intended result is this:
The "Standings List" that gets overlayed on the video has two parts:
- `leader_window_size` (Leader Standing Lines): This is the number of positions, 1-n, that should always be displayed in the standings list. Setting this, for example, to 5, would show positions 1-5 at all times.
- `field_window_size` (Target Standing Lines): This is the number of positions, centered on the "observed" (target) car (typically your car!) shown below the above lines. Setting this, for example, to 5, with the observed car in position 10 would show positions 8-12.
    - There's additional behavior that should be obvious if the observed car is in the "leader window" or at the end of the field. The easiest way to say it, however, is that the total number of lines displayed AT ALL TIMES is equal to `leader_window_size` + `field window_size`

Example uses:
- You have a field of 16 cars. You want to show the top 10 in the overlay, and don't care about having your position (should it be outside that top 10) shown at all times. You'd set `leader_window_size` to 10, and `field_window_size` to 0.
- You have a field of 32 cars. You don't care about the leaders of the race; you just want to show the cars in your immediate vicinity: The 3 ahead of you and the 3 behind you. You'd set `leader_window_size` to 0 and `field_window_size` to 7 (3 ahead + 3 behind + 1 you)
- You have a field of 50 cars. You want to show the top 6 cars at all times, plus the car ahead and behind you at all times. You'd set `leader_window_size` to 6, and `field_window_size` to 3.

I'll run your data through... `leader_window_size` 11 SHOULD catch everyone, but if it's not, something's going on. I think I have an inkling of what that might be if it's broken, though.

**Comment by Michel-NL** [comment]
Aha nice feature :) Could you put this on the wiki?

What if I wanted to show all drivers, could I use 0 for both settings?
With 16 drivers I want them all on the Standings List.

**Comment by Michel-NL** [comment]
> I'll run your data through...  leader_window_size  11 SHOULD catch everyone, but if it's not, something's going on. I think I have an inkling of what that might be if it's broken, though.

Let my first create an -s video. Because I didn't placed the settings at all in the config file.

**Comment by Michel-NL** [comment]
Settings used
  "field_window_size" : 11,
  "leader_window_size" : 0,

Gives me 11 drivers so thats ok for me, because the race has 11 drivers.

**Comment by SenorPez** [comment]
Changed the defaults for "result_lines" and "leader_window_size" to 16 and "field_window_size" to 0. Using these settings seems to render the video correctly.
