### ISSUE TITLE
60 FPS and set video resolution option

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#110]
With the PS4 Pro we now could stream to YouTube with 1080 and 60FPS.
Replayenhancer is rendering video's with 30FPS.
Is it possible to let the use decide the output resolution and FPS like a dropdown box on the configuration editor?

**Comment by SenorPez** [comment]
That's doable.

The resolution is set by the input video, if provided, so giving it a 1080 video should produce a 1080 output.
The FPS is actually settable, I just haven't exposed it.

It'll be important to note, however, that if you're rendering a 60 fps video you need to make sure you're capturing telemetry with at least 60 packets per second!

**Comment by SenorPez** [comment]
Slight change to the logic:

If frames per second is set with the `-f` flag, that's used.
If frames per second is not set with the `-f` flag:
  - If a source video is provided, the frames per second of the source video is used.
  - If a source video is not provided, frames per second is set to 30.

**Comment by Michel-NL** [comment]
Is it possible to add this option to the UI?
Like a on/off button on the Options tab.

Do you think it is even possible to capture 60 packets per second? What should be the UDP settings in PC for this?

**Comment by SenorPez** [comment]
Yes, that should be added to the UI. I meant to get to it before my holiday break, but I just couldn't find the time.

60 packets a second is doable. In fact, by planning or providence, UDP 1 (the maximum packet output rate) is 60 packets a second. And the packets themselves are small; storage is cheap.
