### ISSUE TITLE
Players disconnecting in race are not in the final results

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#112]
I don't know if you wanted it to be this way, but drivers who disconnect from the race are not showing up on the results screen. 
![aor gt3 pro league - round 3 - road america replay _starting_grid](https://cloud.githubusercontent.com/assets/16852542/21027325/9d7f7c94-bd90-11e6-82bb-b650bfdf2e10.png)
![aor gt3 pro league - round 3 - road america replay _results](https://cloud.githubusercontent.com/assets/16852542/21027330/a3debb5e-bd90-11e6-9b0c-a780ba22623e.png)

**Comment by SenorPez** [comment]
No, they should still show up in the results!

**Comment by Michel-NL** [comment]
They also disappear from the standings list in the overlay.
In lap 7 the driver Wimstradamus disconnect https://youtu.be/LPtWFRucK6g

**Comment by SenorPez** [comment]
That's as planned. Drivers who drop out of the race slide out (to the left) of the standings. But they should still show up in the final standings.

**Comment by SenorPez** [comment]
Turns out they do show up. I tested it with a few datasets and they properly list into the final results.

What's probably happening is another bad default by me. Check your configuration file; there's a key called `result_lines` that's probably set to 10. Set that to a larger number to control the number of lines shown on the cards.

I've changed the default to a more reasonable number of 16 (from 10) in another check-in.

**Comment by SenorPez** [comment]
Never mind, I see the problem now. Still an issue.

**Comment by SenorPez** [comment]
@Michel-NL Can you try this with your dataset to confirm it works? It works with the test data I have. Thanks!

**Comment by Michel-NL** [comment]
I will try it later this day.

**Comment by Michel-NL** [comment]
If I do pip install --upgrade replayenhancer I don't get an upgrade for the code. Or should it work with the version I have?

**Comment by SenorPez** [comment]
Sorry about that. I meant to publish a release candidate to the repository, but ran out of time! It should publish out tonight if everything builds correctly.

**Comment by SenorPez** [comment]
It's published. Note that, due to `pip`'s algorithms, you'll need to specify the Release Candidate specifically.

`pip install replayenhancer==0.5.1rc1`

Note the 2 `=` signs.

**Comment by Michel-NL** [comment]
It's working now. Good job!
