### ISSUE TITLE
Create Demo to Include in Repository

### ISSUE THREAD

**Issue by SenorPez** [SenorPez/project-cars-replay-enhancer#14]
Include a set of telemetry data, a video, and a configuration file that can be used to verify a system is properly configured.

**Comment by SenorPez** [comment]
Actual demo files are too big to checkin. (As a huge chunk of binary data, primarily consisting of the source video, it's also probably not appropriate to checkin.)

I've hosted them on Dropbox (we'll see how long that lasts) and written a wiki page that describes the entire demo procedure.

https://github.com/SenorPez/project-cars-replay-enhancer/wiki/Demo

**Comment by SluggishJohan** [comment]
Hi SenorPez, nice work! It seems that the demo file on Dropbox is no longer available. So could you please re-upload the related files again? Thanks!
