### ISSUE TITLE
Race Start and Finish Detection Fails

### ISSUE THREAD

**Issue by SenorPez** [SenorPez/project-cars-replay-enhancer#30]
On some telemetry files, race start detection is failing. This seems to happen if there's no restarts, because there are no zeros, which are used to detect race start.

**Comment by Michel-NL** [comment]
This fix solves this error:
PS D:\pc\project-cars-replay-enhancer-master> python .\show_participants.py .\globals_race4.py
Traceback (most recent call last):
  File ".\show_participants.py", line 14, in <module>
    get_telemetry(g.sourcetelemetry)
  File "D:\pc\project-cars-replay-enhancer-master\get_telemetry.py", line 45, in get_telemetry
    raceStart = [i for i, data in reversed(list(enumerate(g.telemetryData[:raceFinish]))) if int(data[9]) & int('111', 2) == 0][0] + 1
IndexError: list index out of range

Into this:
PS D:\pc\project-cars-replay-enhancer-0.2.1-devel> python .\show_participants.py .\globals_race4.py
 0: RobinNova
 1: sp0rtl1fe
 2: DeTjuK
 3: dennisvandenb
 4: fonsmeister
 5: M1d4s010
 6: roflmannetje
 7: Ha4anova
 8: Michel--NL
 8: MrMistral
 8: MxGD22al
 9: BoereJack
