### ISSUE TITLE
Standings.py font location error

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#38]
I'm getting an error on line 96 and 100
`font = ImageFont.truetype("/usr/share/fonts/truetype/Roboto/Roboto-Regular.ttf", font_size)`
I dont have that font on my system. Is it possible to change the code to use the input from the user?
`font = self.replay.font`

**Comment by Michel-NL** [comment]
hmm changing it with `font = self.replay.font, font_size` gives me this error

>   File "/home/michel/project-cars-replay-enhancer-0.3-devel/Standings.py", line 97, in __sector_rectangles
>     while font.getsize("PIT")[0] > width_target and \
> AttributeError: 'tuple' object has no attribute 'getsize

**Comment by SenorPez** [comment]
Is this in the 0.3-dev branch? The new configuration scripts ask for the font and heading font, and you can specify any path you'd like.

**Comment by SenorPez** [comment]
@Michel-NL Fixed. The PIT size detection was still using a hardcoded font. It should now use whatever font you're using for the rest of the interface.

**Comment by Michel-NL** [comment]
Leave a comment
