### ISSUE TITLE
Enter previous series point...required?

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#41]
With the latest version it is required to enter previous series point for the drivers.
I like the future but don't always use it. I believed it was an option at previous versions.

> Include team data for drivers?
> [Y/n]--> n
> Entering data for Bacotje30.
> Enter display name override for Bacotje30.
> (Bacotje30)-->
> Enter abbreviated name override for Bacotje30.
> (Used by some modules for space saving.)
> (Bacotje30)-->
> Enter car for Bacotje30.
> ()--> Ginetta G55 GT4
> Enter previous series points for Bacotje30.
> ()-->

**Comment by SenorPez** [comment]
It should really be defaulting to zero. I'll take a look at that.

In the meantime, to work around it, you can enter 0 for the first driver and -1 for the second (to use the previous value for the remaining drivers).

**Comment by SenorPez** [comment]
I'll look into just making this all optional, too. It probably won't happen right away, but I've created #42 to remind me of it.

**Comment by SenorPez** [comment]
This now should properly default to zero. See also #42.
