### ISSUE TITLE
Make Points and Series Standings Optional

### ISSUE THREAD

**Issue by SenorPez** [SenorPez/project-cars-replay-enhancer#42]
A point structure and the Series Standing card should be optional.

Modify Configuration to account for an optional point structure.
Modify Results screen to drop the column if it's not used.
Modify Series Standing screen to not appear if it's not used.

**Comment by SenorPez** [comment]
Points for a race are now optional.

Points are disabled by entering a `0` for position 1. This:
- Set the points structure to null in the JSON file.
- Disables the display of the points column in the Results card after the race.
- Disables the display of a Series Standing card after the race.

A Champion card can still be shown, regardless of points structure status. I mean, a 1-race Champion is kind of weird, but if that's your thing, go for it.

**Comment by Michel-NL** [comment]
Is it possible to put a info text like with 

> Enter points scored for finish position 1
> Enter 0 to disable points for this race

now you have to guess to use 0 and at the next driver you can use -1 

> Enter previous series points for Bacotje30.
> ()--> 0
> Entering data for dennisvandenb.
> Enter display name override for dennisvandenb.
> (dennisvandenb)-->
> Enter abbreviated name override for dennisvandenb.
> (Used by some modules for space saving.)
> (dennisvandenb)-->
> Enter car for dennisvandenb.
> Enter -1 to use Ginetta G55 GT4 for remaining drivers.
> (Ginetta G55 GT4)-->
> Enter previous series points for dennisvandenb.
> Enter -1 to use 0 for remaining drivers.
> (0)--> -1

**Comment by SenorPez** [comment]
I think I know what you're asking for, and it seems like an easy fix. Basically, you're asking for the first driver (in this case, Bacotje30) to default to 0 and give the -1 option on his prompt as well, instead of having to add 0 and then put in -1 on the next driver?

That's doable.

**Comment by SenorPez** [comment]
(Note that if you disable points structure for a given race, you're not prompted for driver points, since, you know, there's no... POINT.) :laughing:

**Comment by Michel-NL** [comment]
No its not for the racepoints from the actual race but for the "previous series'

ooo wait
It only asks you for the **previous series points** if you enter points for finish score. If you use:

> Enter points scored for finish position 1
> Enter 0 to disable points for this race
> 0--> 0

then you don't get the question:

> Enter previous series points for Bacotje30.
> ()-->

What I like is that with the question for the first driver to enter **previous series points** you get this:

> Enter previous series points for Bacotje30.
> Enter -1 to disable previous points for this race
> ()-->

Hope you understand :)

**Comment by SenorPez** [comment]
I'm not sure the latest change (defaulting points to zero) is **quite** what you want, but it's close?

If I'm still not understanding, can you describe the difference between setting all previous points to zero and disabling previous points?

**Comment by Michel-NL** [comment]
Put this one on hold...I have to make it clearer it the next days.
Now focusing on getting two races ready for YouTube with the replay-enhancer :)
