### ISSUE TITLE
path to video_cache error

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#43]
I think the error is when I need to enter the path for the video_cache file

> Enter abbreviated name override for wimstradamus.
> (Used by some modules for space saving.)
> (wimstradamus)-->
> Enter car for wimstradamus.
> Enter -1 to use Ginetta G55 GT4 for remaining drivers.
> (Ginetta G55 GT4)--> Aston Martin V8 Vantage GT4
> 
> Configuration data written to race6.json
> Traceback (most recent call last):
>   File "ReplayEnhancer.py", line 708, in <module>
>     ReplayEnhancer.new_configuration()
>   File "ReplayEnhancer.py", line 438, in new_configuration
>     config.new_configuration()
>   File "/home/michel/project-cars-replay-enhancer-0.3-devel/Configuration.py", line 956, in new_configuration
>     with open(os.path.realpath(self.video_cache), 'r') \
>   File "/usr/lib/python3.4/posixpath.py", line 372, in realpath
>     path, ok = _joinrealpath(filename[:0], filename, {})
> TypeError: 'NoneType' object is not subscriptable
> michel@ubuntu:~/project-cars-replay-enhancer-0.3-devel$

**Comment by Michel-NL** [comment]
Running the command `michel@ubuntu:~/project-cars-replay-enhancer-0.3-devel$ python3 ReplayEnhancer.py -c race6.json`
wil read the config from above and continues

Looks like the error only acts with creating the config with a new/empty config

**Comment by SenorPez** [comment]
You must have found this right at the same time I did. Don't get used to changes coming this fast... luckily, I have Wifi right now. Unluckily, I'm waiting on a meeting that was supposed to start 45 minutes ago! LOL

Good news for this error, however: Your configuration file was actually written before this error, so you don't lose anything.

Checkin made that fixes this.

**Comment by Michel-NL** [comment]
haha :)
tested again and the error is gone :+1:
