### ISSUE TITLE
Champion screen positions gained or lost feature

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#47]
Is it possible to show in the campion screen how many positions you gained or lost?

This is just a example. You could do better ;-)
![postions](https://cloud.githubusercontent.com/assets/16852542/13123722/dd111dce-d5bd-11e5-8ca1-451c5dbd788f.jpg)

**Comment by SenorPez** [comment]
Implemented in the 0.5 Release. Logic is as follows:

- For the Results Screen, it's used at all times. In fact, the "default" Results screen is never actually used.
- For the Series Standings screen, it's used if the previous points values weren't all zero (i.e., this wasn't the first race in the series).
