### ISSUE TITLE
Entering color code error

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#68]
michel@SRV-VM-UBUNTU:~/master$ python3 ReplayEnhancer.py
No configuration file provided.
Creating new configuration file.
Creating configuration file.
Press CTRL+C at any time to abort.
Enter destination file for configuration.
.json file extension will be added automatically.
CAUTION: Existing file contents will be overwritten.
--> race10
Enter source video file.
Enter -1 for no file. Video will be rendered on a transparent background.
--> ../data/video/Project Cars Le circuit Bugatti McLaren 12C GT3.mp4
Enter source telemetry directory.
--> ../data/telemetry/racedata10/
Enter output video file.
--> ../data/video/Project Cars Le circuit Bugatti McLaren 12C GT3-output.mp4
Enter path to font.
--> ../data/fonts/Verdana.ttf
Enter size of font.
15--> 11
Enter font color.
Color should be entered as three integers, separated by commas, representing Red, Green, and Blue values.
(0, 0, 0)--> 61,42,42
Traceback (most recent call last):
  File "ReplayEnhancer.py", line 998, in <module>
    ReplayEnhancer.new_configuration()
  File "ReplayEnhancer.py", line 540, in new_configuration
    config.new_configuration()
  File "/home/michel/master/Configuration.py", line 223, in new_configuration
    for x in font_color]):
  File "/home/michel/master/Configuration.py", line 223, in <listcomp>
    for x in font_color]):
TypeError: unorderable types: str() >= int()
michel@SRV-VM-UBUNTU:~/master$

**Comment by SenorPez** [comment]
Oops.

Just checked the change into the 0.3.2 development branch; not sure how this snuck through the testing. If you want to edit your files, it's super easy: Change "==" to "=" on lines 220 and 536. (See the checkin for exact changes, or just grab the 0.3.2 development branch.)

**Comment by Michel-NL** [comment]
okay that worked.
I used the main branch, maybe you could update the code of the main branch? or else other people would have the same problem ;-)

**Comment by SenorPez** [comment]
Yeah, I'll push out an update before the end of the day, just to nip this one in the bud.
