### ISSUE TITLE
outputs folder with -u option?

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#83]
Had to create manually the **outputs** folder or else the program crashes

> Stream mapping:
>   Stream #0:0 -> #0:0 (rawvideo (native) -> png (native))
> [image2 @ 0x4295f80] Could not open file : outputs/results.png
> av_interleaved_write_frame(): Input/output error

**Comment by SenorPez** [comment]
Closing this as it's on the old architecture. If this can still occur in the current build (which includes more error checking), please file a new issue.
