### ISSUE TITLE
-u option stops after creating the file options/results.png

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#84]
With the -u option the program stops without an error after creating the results.png. The whole proces takes about 2 seconds and then stops.

> michel@SRV-VM-UBUNTU:~/0.4-devel$ python3 ReplayEnhancer.py -u race1.json
> Creating video with custom settings.
> Using Track: Catalunya
> michel@SRV-VM-UBUNTU:~/0.4-devel$

**Comment by SenorPez** [comment]
Hmm... I can't for the life of me figure out what might be causing this.

It **could** be related to some of the deficiencies currently in the 0.4 branch, or not. There **are** some gaps, currently, in what the new structure supports. I'm adding features as fast as I can, though!

If you run it without the -u option, does the replay successfully create?

And if you could ZIP up the telemetry and your JSON configuration file, that might help investigation!

Thanks!

**Comment by Michel-NL** [comment]
Without the -u option the replay is successfully. 
Some of the data (video, fonts, images) is outside the execution tree (did see that bug), should that be a problem? You can see the directories in JSON file.

Link for the data: https://1drv.ms/u/s!AkpjgvuA0hKBksZZbxSP3VZ4rDyjVA

**Comment by SenorPez** [comment]
Closing this as it was on the old architecture. The `-u` option is now deprecated; `GTStandings` is now the default standings tree. If it's still causing a problem, reopen!
