### ISSUE TITLE
unicodecsv is needed in 0.3.2

### ISSUE THREAD

**Issue by keppo070** [SenorPez/project-cars-replay-enhancer#89]
Traceback (most recent call last):
File "ReplayEnhancer.py", line 21, in <module>
import unicodecsv as csv
ImportError: No module named 'unicodecsv'

which is not on the needed list. I use python 3.5.1

**Comment by SenorPez** [comment]
Hmm... I could have sworn it was installed along with one of the other dependencies, but I'm clearly wrong! This was added to support unicode encoding, as--surprisingly--the default CSV module for Python does _not_!
