### ISSUE TITLE
Position in result screen is not correct

### ISSUE THREAD

**Issue by keppo070** [SenorPez/project-cars-replay-enhancer#90]
We had a league race but no.7 is DSQ so is no.9 but no.8 has crossed the lne bet has problaly driven less rounds than no.7

Shouldn't the DSQ/DNF not positioned lower in the result screen

http://i.imgur.com/Dlc005a.png

**Comment by SenorPez** [comment]
Yes, the DNF should be below position 8; I'm not sure what exactly is going on here. It's showing the same number of laps completed, less time, but a DNF.

It's also _properly_ assigning 0 points to the DNF; is 8 points correct for the person in position 8 (should be in position 7), or should that be 9 points?

Could you upload the `tele.csv` that's generated when running this? I'd like to take a look at the data and see exactly where my parsing (or, possibly, Project CARS data output) is having problems!

## 

What really should happen is a bit more configurability for DNFs and not-classified. I'm open to suggestions; some race series, for example, require you to complete a certain amount of distance to be classified; others require you to be running at the end.

**Comment by keppo070** [comment]
original video https://youtu.be/n1EfyX41Jqs
edited video https://youtu.be/t9neIa4ik9w

telecsv :: https://drive.google.com/file/d/0B-yYJgPCab3IUEhhQUhmTmJ3VUE/view?usp=sharing 

The file is way to big to upload otherwise :-)

**Comment by keppo070** [comment]
Just checking up I noticed you asked an other question. The first 15 receive points. Your assumption is correct. No.7 should be awarded 9 points and no.8 should be awarded 8 points
25 20 16 13 11 10 9 8 7 6 5 4 3 2 1

My suggestion would be too do it the way ProjectCars qualifies the results like in my original video @1:09:10

**Comment by SenorPez** [comment]
Tested this and the rewrite seems to have resolved the issue. If you do see it happen again, please feel free to open a new issue!

(Completely honestly: I wasn't sure why this was happening, and I'm not sure what fixed it, but hey, I'll take it!)
