### ISSUE TITLE
Help for starting up PIP version

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer#99]
Hi SenorPez,

Trying to use the PIP version, but I need some assistant for this :)

**Using:**
Ubuntu Server 16.04.1
Python 3.5.2
PIP 9.0.1 (Download: https://bootstrap.pypa.io/3.2/get-pip.py)

**Installation:**
sudo python3 get-pip.py

> michel@SRV-VM-UBUNTU:~$ sudo python3 get-pip.py
> [sudo] password for michel:
> The directory '/home/michel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/michel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting pip<8
>   Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
>     100% |████████████████████████████████| 1.1MB 691kB/s
> Collecting setuptools
>   Downloading setuptools-28.8.0-py2.py3-none-any.whl (472kB)
>     100% |████████████████████████████████| 475kB 1.6MB/s
> Collecting wheel
>   Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
>     100% |████████████████████████████████| 69kB 6.4MB/s
> Installing collected packages: pip, setuptools, wheel
> Successfully installed pip-7.1.2 setuptools-28.8.0 wheel-0.29.0
> You are using pip version 7.1.2, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

sudo pip install --upgrade pip

> michel@SRV-VM-UBUNTU:~$ sudo pip install --upgrade pip
> The directory '/home/michel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/michel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting pip
>   Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
>     100% |████████████████████████████████| 1.3MB 614kB/s
> Installing collected packages: pip
>   Found existing installation: pip 7.1.2
>     Uninstalling pip-7.1.2:
>       Successfully uninstalled pip-7.1.2
> Successfully installed pip-9.0.1

sudo pip install replayenhancer

> michel@SRV-VM-UBUNTU:~$ sudo pip install replayenhancer
> The directory '/home/michel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/michel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting replayenhancer
>   Downloading replayenhancer-0.5rc1-py3-none-any.whl (224kB)
>     100% |████████████████████████████████| 225kB 4.1MB/s
> Collecting moviepy (from replayenhancer)
>   Downloading moviepy-0.2.2.11.tar.gz (107kB)
>     100% |████████████████████████████████| 112kB 6.0MB/s
> Collecting natsort (from replayenhancer)
>   Downloading natsort-5.0.1-py2.py3-none-any.whl
> Collecting pillow (from replayenhancer)
>   Downloading Pillow-3.4.2-cp35-cp35m-manylinux1_x86_64.whl (5.6MB)
>     100% |████████████████████████████████| 5.6MB 335kB/s
> Collecting tqdm (from replayenhancer)
>   Downloading tqdm-4.9.0-py2.py3-none-any.whl (42kB)
>     100% |████████████████████████████████| 51kB 10.4MB/s
> Collecting numpy (from moviepy->replayenhancer)
>   Downloading numpy-1.11.2-cp35-cp35m-manylinux1_x86_64.whl (15.6MB)
>     100% |████████████████████████████████| 15.6MB 125kB/s
> Collecting decorator (from moviepy->replayenhancer)
>   Downloading decorator-4.0.10-py2.py3-none-any.whl
> Collecting imageio (from moviepy->replayenhancer)
>   Downloading imageio-1.6.zip (3.3MB)
>     100% |████████████████████████████████| 3.3MB 589kB/s
> Installing collected packages: numpy, decorator, imageio, tqdm, moviepy, natsort, pillow, replayenhancer
>   Running setup.py install for imageio ... done
>   Running setup.py install for moviepy ... done
> Successfully installed decorator-4.0.10 imageio-1.6 moviepy-0.2.2.11 natsort-5.0.1 numpy-1.11.2 pillow-3.4.2 replayenhancer-0.5rc1 tqdm-4.9.0

Looks like the installation went OK 👍 

Now I want to use packetgrab to capture the UDP stream. How do I do that? Early versions I used **python3 packetgrab.py**, but with the PIP installation all the files are installed somewhere else?

Second thing I tried (even with no packets available) is **replayenhancer -s config.json**. The error I get is:

> michel@SRV-VM-UBUNTU:~$ replayenhancer -s config.json
> Traceback (most recent call last):
>   File "/usr/local/bin/replayenhancer", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.5/dist-packages/replayenhancer/__init__.py", line 240, in main
>     sync=args.sync)
>   File "/usr/local/lib/python3.5/dist-packages/replayenhancer/__init__.py", line 25, in make_video
>     configuration = json.load(open(config_file))
> FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by Michel-NL** [comment]
Because of the comment with -H flag I did a new install with the -H flag (don't know what it means). But the yellow warning are gone.

> michel@SRV-VM-UBUNTU:~$ sudo -H python3 get-pip.py
> Collecting pip<8
>   Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
>     100% |████████████████████████████████| 1.1MB 688kB/s
> Collecting setuptools
>   Downloading setuptools-28.8.0-py2.py3-none-any.whl (472kB)
>     100% |████████████████████████████████| 475kB 1.5MB/s
> Collecting wheel
>   Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
>     100% |████████████████████████████████| 69kB 5.5MB/s
> Installing collected packages: pip, setuptools, wheel
> Successfully installed pip-7.1.2 setuptools-28.8.0 wheel-0.29.0
> You are using pip version 7.1.2, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> michel@SRV-VM-UBUNTU:~$ sudo -H pip install --upgrade pip
> Collecting pip
>   Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
>     100% |████████████████████████████████| 1.3MB 608kB/s
> Installing collected packages: pip
>   Found existing installation: pip 7.1.2
>     Uninstalling pip-7.1.2:
>       Successfully uninstalled pip-7.1.2
> Successfully installed pip-9.0.1
> michel@SRV-VM-UBUNTU:~$ sudo -H pip install replayenhancer
> Collecting replayenhancer
>   Downloading replayenhancer-0.5rc1-py3-none-any.whl (224kB)
>     100% |████████████████████████████████| 225kB 3.3MB/s
> Collecting moviepy (from replayenhancer)
>   Downloading moviepy-0.2.2.11.tar.gz (107kB)
>     100% |████████████████████████████████| 112kB 5.0MB/s
> Collecting tqdm (from replayenhancer)
>   Downloading tqdm-4.9.0-py2.py3-none-any.whl (42kB)
>     100% |████████████████████████████████| 51kB 7.4MB/s
> Collecting natsort (from replayenhancer)
>   Downloading natsort-5.0.1-py2.py3-none-any.whl
> Collecting pillow (from replayenhancer)
>   Downloading Pillow-3.4.2-cp35-cp35m-manylinux1_x86_64.whl (5.6MB)
>     100% |████████████████████████████████| 5.6MB 338kB/s
> Collecting numpy (from moviepy->replayenhancer)
>   Downloading numpy-1.11.2-cp35-cp35m-manylinux1_x86_64.whl (15.6MB)
>     100% |████████████████████████████████| 15.6MB 125kB/s
> Collecting decorator (from moviepy->replayenhancer)
>   Downloading decorator-4.0.10-py2.py3-none-any.whl
> Collecting imageio (from moviepy->replayenhancer)
>   Downloading imageio-1.6.zip (3.3MB)
>     100% |████████████████████████████████| 3.3MB 580kB/s
> Building wheels for collected packages: moviepy, imageio
>   Running setup.py bdist_wheel for moviepy ... done
>   Stored in directory: /root/.cache/pip/wheels/ba/fa/af/be4051961aa23c8566906e9a3bd5f7bb57ac2c3f3c43f09dbc
>   Running setup.py bdist_wheel for imageio ... done
>   Stored in directory: /root/.cache/pip/wheels/47/89/47/c6d7547b6805a7fc1a84bceae9f382308afeebaaa8ab6a8deb
> Successfully built moviepy imageio
> Installing collected packages: numpy, decorator, imageio, tqdm, moviepy, natsort, pillow, replayenhancer
> Successfully installed decorator-4.0.10 imageio-1.6 moviepy-0.2.2.11 natsort-5.0.1 numpy-1.11.2 pillow-3.4.2 replayenhancer-0.5rc1 tqdm-4.9.0

**Comment by SenorPez** [comment]
The quick fix is readding packet capture support. It somehow got dropped. It can be executed with `packetcapture` at the command line. You should be able to get it by running `pip upgrade replayenhancer`, though it might take a while for the package to update on the server to RC2.

The sudo thing is in fact an environment setting, and just something that has to be done, unfortunately. I have two systems I use for testing, and one of them requires it. Just part of the "fun" of various Linux distributions.

Parsing through the rest today. Note that I probably wasn't clear... instead of "config.json" you should substitute your own configuration file, created by the other project... or you can use existing configuration files; they're backward compatible.

**Comment by Michel-NL** [comment]
> Parsing through the rest today. Note that I probably wasn't clear... instead of "config.json" you should substitute your own configuration file, created by the other project... or you can use existing configuration files; they're backward compatible.

Ah you mean https://github.com/SenorPez/project-cars-replay-enhancer-ui. Should have think about that ;-)

BTW going to setup this al up on Windows 10 with Bash. No server or VM needed anymore 👍 
Will let you know if it works. Should be easier for others Windows users to use it.
https://msdn.microsoft.com/commandline/wsl/about 

Update: Windows 10 Bash is a no go. It will not run and since the Bash thing is a Beta I will not look further in it. At the moment Ubuntu is the way to go for me.

**Comment by Michel-NL** [comment]
Closing this issue. User could use the command **packetcapture** and we have the java **packetcapture.jar** (https://github.com/SenorPez/project-cars-replay-enhancer-ui/releases)
